.markdown-lint.yml
If we would like to add specific tags in the future, we could so via a whitelist from now on: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033---inline-html
=> refactor(markdownlint): remove inline HTML allowance

packages/components/src/components/button/model.ts, packages/components/src/components/card/model.ts, packages/components/src/components/divider/divider.lite.tsx, packages/components/src/components/divider/model.ts, packages/components/src/components/icon/model.ts, packages/components/src/components/input/input.lite.tsx, packages/components/src/components/input/model.ts, packages/components/src/components/tab-bar/model.ts, packages/components/src/components/tab/model.ts
reverted some parts out of https://github.com/db-ui/mono/pull/256
=> fix: pipeline

package-lock.json, packages/foundations/scripts/color-placeholders-generator.js, packages/foundations/tokens/zeplin.json
Some colors changed by UX definitions and for accessibility.
Added "elements" color to have extra colors for icons in some components like `infotext`
=> chore: update colors from zeplin

.github/dependabot.yml
re-timed the dependabot update checks as they might take a little longer especially due to the missing grouping possibility.
=> refactor: new timing for dependabot updates

packages/foundations/scss/_font-faces.scss
to the stack of files that are possible to get referenced.
We're not adding this to the set of tokens, as this font isn't officially part of the Design System so far.
=> refactor: added DB Screen Sans Digital Regular

packages/components/_templates/mitosis/new/react-showcase-component.ejs.t
this declaration lead to an error during build:
> The 'type' modifier cannot be used on a named import when 'import type' is used on its import statement. (3:14)
=> fix: generate components template

packages/components/src/components/radio/radio.scss
`:user-invalid` selector will soon get supported by all evergreen browsers, but we need to ensure that those aren't conflicting with non-supporting browsers.
=> fix: selector on new pseudo-selector

.github/dependabot.yml, package-lock.json, package.json
We're currently facing conflicts within the lock file due to [TypeScript being expected in version 5 by `xo`](https://github.com/db-ui/mono/pull/802), but most of our other dependencies still use version 4.
=> refactor: rolled back xo version

packages/components/src/components/input/input.lite.tsx, packages/components/src/components/radio/model.ts, packages/components/src/shared/model.ts
Resolves https://github.com/db-ui/mono/issues/870
=> refactor: generalizing some states

packages/components/src/components/input/input.scss, packages/components/src/components/radio/radio.scss, packages/foundations/scripts/color-placeholders-generator.js, packages/foundations/scss/color/_color-variants.scss
It's simpler to not use the `:not` selector.
=> chore: simplified selectors

packages/components/src/components/drawer/drawer.scss
The opened "non full width" drawer without a backdrop needs some visual boundary on the "open" side – therefor we'll add a box-shadow of `elevation-4`.
=> refactor(drawer): integrated feedback

.stylelintrc.json, packages/components/src/components/drawer/drawer.lite.tsx, packages/components/src/components/drawer/drawer.scss, packages/components/src/components/drawer/model.ts, packages/components/src/styles/_dialog-init.scss, showcases/react-showcase/src/components/drawer/index.tsx, showcases/shared/drawer.json
Add new attribute for `db-drawer`: `data-emphasis` to control the opacity of the background
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
=> feat: add "weak" emphasis for drawer

.jscpd.json
as this is an output path, we don't want to lint this one
=> refactor(lint): added relevant ignore path to copy and paste linter

.husky/pre-commit, .lintstagedrc
Resolves https://github.com/db-ui/mono/issues/1432
I've tested this by checking in an invalid markdown file (and deactivating markdownlint just for that commit), and trying to commit another invalid file afterwards within another commit – within this commit response message out of `lint-staged`& `markdownlint`, only the newly checked in invalid file has been mentioned, whereas with the previous code both would have been mentioned.
=> refactor: doing markdownlint only for the staged files

showcases/patternhub/next.config.js, showcases/patternhub/package.json
the following warning gets logged:
> warn "next export" is deprecated in favor of "output: export" in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
=> refactor: next export is deprecated

packages/components/src/components/accordion/accordion.lite.tsx, packages/components/src/components/alert/alert.lite.tsx, packages/components/src/components/badge/badge.lite.tsx, packages/components/src/components/brand/brand.lite.tsx, packages/components/src/components/card/card.lite.tsx, packages/components/src/components/divider/divider.lite.tsx, packages/components/src/components/icon/icon.lite.tsx, packages/components/src/components/infotext/infotext.lite.tsx, packages/components/src/components/link/link.lite.tsx, packages/components/src/components/main-navigation/main-navigation.lite.tsx, packages/components/src/components/navigation-item/navigation-item.lite.tsx, packages/components/src/components/page/page.lite.tsx, packages/components/src/components/section/section.lite.tsx, packages/components/src/components/tab-bar/tab-bar.lite.tsx, packages/components/src/components/tab/tab.lite.tsx, packages/components/src/components/tag/tag.lite.tsx
We didn't pass the `props.id` to every component, which makes it inaccessible to DOM or e2e tests.
=> fix: add missing id for components to use them from DOM or e2e tests

packages/components/src/components/button/button.scss
The button didn't have `fit-content` for `inline-size`. 
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> fix: issue with button not having auto width

packages/components/src/components/tooltip/tooltip.scss, packages/components/src/styles/_popover-component.scss
Add `font-style: normal;` for popover
Resolves https://github.com/db-ui/mono/issues/1761
=> fix: popover font-style

packages/components/src/components/accordion/accordion.lite.tsx, packages/components/src/components/accordion/model.ts, showcases/patternhub/scripts/get-example-file.js
It's not possible to have an initial state for open items in accordion.
=> feat: add initOpenIndex to open accordion items initially

packages/components/scripts/post-build/components.js
- `DBHeader` for `angular` had the wrong event handler, the drawer wasn't closeable
=> fix: issue with angular header close event

.lintstagedrc.js
- `lintstaged` is triggered even when resolving a merge conflict
- this will trigger the `generate-icon-fonts` if new icons are added
- it isn't necessary to trigger the generation again -> so we shouldn't run the generation process
=> fix: remove generating icon-fonts from lintstaged

packages/components/src/components/accordion-item/docs/Angular.md, showcases/angular-showcase/src/app/components/default.component.html
The term `slot` is typically not used in the angular world. It's called `content projection` here.
see: https://angular.dev/guide/components/content-projection
closes #1498
=> docs(@db-ui/ngx-components): change term to content projection instead of slot

packages/components/src/components/checkbox/checkbox.scss, packages/components/src/components/radio/radio.scss, packages/components/src/styles/_form-components.scss
Add correct `:user-valid` for checkbox and select
=> fix: issue with `user-valid` for form-components

packages/components/src/components/drawer/drawer.lite.tsx, packages/components/src/components/drawer/model.ts, packages/components/src/shared/model.ts
closes #2594
- Handle backdrop click with additional `event.type===click`
- Pass `event` to `onClose` for user to check which event was fired
=> fix: issue with drawer closing on every key

packages/components/src/shared/model.ts
The `center` string literal was missing for `alignment` for `DBTabs` 
=> fix: missing alignment property (center)

packages/foundations/tailwind/tailwind-tokens.json
closes https://github.com/db-ui/theme-builder/issues/329
Esbuild was not able to append keys in the `tailwind-token.json` which start with a number like `3xs` 
=> fix: issue with tailwind tokens causing esbuild warning

packages/components/src/styles/_popover-component.scss
=> fix: issue with popover visibility, replaced with display:none

packages/components/src/components/card/card.scss
Currently Links do not have a text decoration (underline) because of this global style
=> fix: remove global link style from DBCard

packages/components/src/styles/_tag-components.scss
Static tag had wrong bg-lvl (1), but needs bg-lvl-3
=> fix: static tag color to align with design

showcases/screen-reader/__snapshots__/windows/chromium/DBDrawer-should-autofocus.txt, showcases/screen-reader/default.ts, showcases/screen-reader/tests/drawer.spec.ts
Resolves https://github.com/db-ui/mono/issues/2921
=> fix: issue with wrong snapshot

showcases/react-showcase/src/components/data.ts, showcases/shared/default-component-data.ts, showcases/shared/notification.json
adds optional codeFileName field to components example data, to include all code examples to patternhub
fixes #2863
=> fix: adds optional codeFileName field to components example data

packages/foundations/scss/init/default-fonts.scss
adds text-wrap balance to headlines h1 - h6
resolves #896
=> feat: adds text-wrap balance to headlines h1 - h6

packages/components/src/styles/_form-components.scss, showcases/screen-reader/__snapshots__/windows/chromium/DBInput-required-1.txt
We could set an empty alternative text for the inserted star on required form fields as we don't want to output that glyph e.g. for screenreader users, because we're already setting the correct state by the `required`-HTML-attribute.
=> refactor: overwrite star for screenreader output

packages/components/src/components/tab-item/tab-item.scss, packages/foundations/scss/init/required.scss, showcases/showcase-styles.css
Resolves https://github.com/db-ui/mono/issues/3079
=> fix(safari): restored list-style type for VoiceOver screenreader

packages/foundations/package.json
currently we haven't separated `npx` and `@db-ui/gif` parameters correctly. ~That for we need to add `--` accordingly.~
=> fix: simplification for `@db-ui/gif` parameters

showcases/patternhub/components/version-switcher/version-switcher.tsx
The `latest` entry isn't getting displayed within the version switcher at the moment.
=> fix(version switcher): displaying `latest` entry

README.md
Samsung released the new Internet browser version with an updated Chromium version that even also now supports CSS `light-dark` function on 6th of November.
Resolves https://github.com/db-ui/mono/issues/3117
=> docs: removed Samsung Internet Browser warning

packages/components/src/styles/_form-components.scss
I've noticed that the input form element label is not clickable. This means that its not possible to click on the label to focus on the input element. Is this something that was omitted or something I missed?
Maybe there are other form elements where pointer-events for labels are disabled, e.g. text-area.
=> fix(a11y): allow labels to be clickable

packages/components/src/styles/_form-components.scss
Removed obsolete CSS declaration. It's not clear why we would need to set a specific cursor and couldn't stick with the browsers default (maybe this was related to the declaration we've removed with https://github.com/db-ui/mono/pull/3462).
=> chore: removed obsolete declaration

output/angular/README.md, output/react/README.md, output/vue/README.md
Changed default bundler tool from webpack to rollup, as the later is the successor or the first one.
=> docs: changed from webpack to its successor rollup

packages/components/src/components/tabs/tabs.lite.tsx
Resolves https://github.com/db-ui/mono/issues/3528
Whereas `&` would be perfectly fine at this place to be used within CSS, when executing `.querySelector` or `.querySelectorAll` in JavaScript we would need to use [`:scope`](https://drafts.csswg.org/selectors-4/#the-scope-pseudo) instead, that gets it's [scoping root](https://drafts.csswg.org/selectors-4/#scoping-root) by the documents part on which `.querySelector` or `.querySelectorAll` are based on (the `ref` in our case).
-   [ ] …
=> fix: replaced JavaScript selector

packages/components/src/styles/_form-components.scss
Currently, the select won't open the options while clicking on the label: https://stackoverflow.com/questions/32653002/click-on-label-doesnt-open-select
=> fix: issue with floating label disables click

packages/components/docs/Validation.md, showcases/patternhub/pages/foundations/colors/color-usage-guide.tsx
These places haven't been upgraded in the past.
=> docs: updated to new syntax

packages/components/src/components/select/select.spec.tsx, showcases/e2e/link/link-a11y.spec.ts, showcases/e2e/switch/switch-a11y.spec.ts
Adds some aspects for https://github.com/db-ui/mono/issues/3332
=> refactor: not disable ally test rule anymore

packages/foundations/scss/_absolute.assets-paths.scss, packages/foundations/scss/_default.assets-paths.scss, packages/foundations/scss/_rollup.assets-paths.scss, packages/foundations/scss/_webpack.assets-paths.scss
These variables have been used in our SCSS code previously but we won't need them at the moment.
=> refactor: remove obsolete variable

docs/migration/v0.6.x-to-v0.7.x.md
=> fix(docs): escaping

packages/migration/src/data.ts
Fixes the following bug within migration package
```shell
npx @db-ui/migration --type=v006_v007 --src=./src      
~/.npm/_npx/f73cec7303872e39/node_modules/commander/lib/option.js:342
throw new Error(
^
Error: option creation failed due to '-dry' in option flags '-dry, --dryRun <dryRun>'
- a short flag is a single dash and a single character
- either use a single dash and a single character (for a short flag)
- or use a double dash for a long option (and can have two, like '--ws, --workspace'
```
=> fix: migration commander error

README.md
Mentioning DB Theme at a prominent place, so that it's even also visible besides the description within the package README files.
=> docs(README): mentioning DB Theme at a prominent place

.config/.lintstagedrc.js, .stylelintignore
Regularly we don't want to lint the stylelint config file. But in case of any changes within these files, this might be the only file that is being defined to get linted by `stylelint` through `lint-staged` (which wouldn't work, as it doesn't contain CSS).
=> refactor(stylelint): resilience

__snapshots__/navigation-item/showcase/chromium-highContrast/should-have-same-aria-snapshot/DBNavigationItem-should-have-same-aria-snapshot.yaml, __snapshots__/navigation-item/showcase/chromium/should-have-same-aria-snapshot/DBNavigationItem-should-have-same-aria-snapshot.yaml, __snapshots__/navigation-item/showcase/firefox/should-have-same-aria-snapshot/DBNavigationItem-should-have-same-aria-snapshot.yaml, __snapshots__/navigation-item/showcase/mobile-chrome/should-have-same-aria-snapshot/DBNavigationItem-should-have-same-aria-snapshot.yaml, __snapshots__/navigation-item/showcase/mobile-safari/should-have-same-aria-snapshot/DBNavigationItem-should-have-same-aria-snapshot.yaml, __snapshots__/navigation-item/showcase/webkit/should-have-same-aria-snapshot/DBNavigationItem-should-have-same-aria-snapshot.yaml, packages/components/src/components/navigation-item/model.ts, packages/components/src/components/navigation-item/navigation-item.lite.tsx, packages/components/src/components/navigation-item/navigation-item.scss, showcases/angular-showcase/src/app/components/navigation-item/navigation-item.component.html, showcases/react-showcase/src/components/navigation-item/index.tsx, showcases/shared/navigation-item.json, showcases/vue-showcase/src/components/navigation-item/NavigationItem.vue
* Enable text of navigation-item to break into multiple lines
* Added showcase that demonstrates the use of multi-line text in navigation items.
* Adapted snapshots
* Fixed incorrect padding in showcases for navigations with sub-items
=> feat: enable text of navigation-item to break into multiple lines

package-lock.json, package.json
The new DB Neo Screen font seems to get rendered differently when referenced from locally installed files vs. the web fonts.
Resolves https://github.com/db-ux-design-system/core-web/issues/4075
=> fix(DB Neo): removed local font references

package-lock.json
`package-lock.json` has old wrong entries, created a new one from a clean project
=> chore: create clean package-lock.json

packages/components/configs/angular/index.cjs, packages/components/configs/angular/mitosis.config.cjs, packages/components/configs/mitosis.config.cjs, packages/components/configs/plugins/on-click.cjs, packages/components/configs/react/index.cjs, packages/components/configs/stencil/index.cjs, packages/components/configs/vue/index.cjs, packages/components/src/components/button/button.lite.tsx, packages/components/src/components/link/link.lite.tsx
=> chore: update onClick for button and link with mitosis plugin

docs/migration/v2.x.x-to-v3.0.0.md, packages/components/src/components/button/button.lite.tsx, packages/components/src/components/button/button.scss, packages/components/src/components/button/model.ts, showcases/react-showcase/src/components/button/index.tsx
=> chore: remove button state

packages/components/src/components/input/input.lite.tsx, packages/components/src/components/input/model.ts
=> feat: add `multiple` property for `input[type=file]`

packages/components/src/components/checkbox/checkbox.lite.tsx, packages/components/src/components/custom-select/custom-select.lite.tsx, packages/components/src/components/input/input.lite.tsx, packages/components/src/components/select/select.lite.tsx, packages/components/src/components/textarea/textarea.lite.tsx, showcases/screen-reader/__snapshots__/windows/chromium/DBInput-required-1.txt, showcases/screen-reader/__snapshots__/windows/chromium/DBTextarea-required-1.txt
=> fix: issue with empty `aria-describedby`

packages/foundations/assets/fonts/generate-eu-fonts.ts
Replaced usage of exec with execFile to prevent shell injection risks when running pyftsubset. Arguments are now passed as arrays, and file paths are validated to avoid path traversal attacks. Improves security and reliability of font generation script.
=> refactor: font generation to use execFile for security

packages/foundations/package.json, packages/foundations/scripts/local/generate-icon-overview.ts
From time to time (or more specifically, when the icons overview gets updated), an unformatted file pops up on localhost, and it even also happens that it gets commited by mistake.
To have it correctly formatted, one even already used prettier, but didn't resolve to the configurations. As we partly store some configuration in the standard file `.editorconfig`, which doesn't seem to get resolved by prettier through it's method [`prettier.resolveConfigFile`](https://prettier.io/docs/api#prettierresolveconfigfilefileurlorpath), but only when used via CLI.
=> fix: annoying unformatted document on localhost

packages/components/src/components/button/button.scss
Even also enabled the disabled styling on an `aria-disabled` button.
Resolves https://github.com/db-ux-design-system/core-web/issues/4680
=> refactor(button): enabled the disabled styling

scripts/package.json
We have to run the build previous to checking the docs path. Elsewhere we couldn't determine whether the files exist that are mentioned in the docs.
=> refactor: we'd have to run build previous to checking the docs path

packages/components/src/components/header/header.scss
* Keep burger visible when drawer has content, hide if nav, meta and secondary are empty
closes https://github.com/db-ux-design-system/core-web/issues/4385
=> fix: Keep burger menu visible when drawer has content

.changeset/cyan-scissors-burn.md, packages/components/src/components/select/select.lite.tsx, showcases/angular-showcase/src/app/components/select/select.component.html
The Angular tests are currently failing because of how Angular is handling the first `option` HTML element of a set of `option` HTML elements out of which none is having the `selected` HTML attribute at the very beginning.
=> fix(select): Angular tests

packages/components/src/components/checkbox/docs/Angular.md, packages/components/src/components/checkbox/docs/HTML.md, packages/components/src/components/checkbox/docs/React.md, packages/components/src/components/checkbox/docs/Vue.md
Die Antwort aus dem https://github.com/db-ux-design-system/core-web/issues/4225 soll auch in der Doku der Komponente [How to use](https://design-system.deutschebahn.com/core-web/version/v3.1.4/components/data-input/checkbox/how-to-use) entsprechend dokumentiert sein.
=> docs(checkbox): add formatted infotext examples for Angular, React & Vue

.changeset/shaggy-ligers-grow.md, output/angular/package.json, output/react/package.json, output/stencil/package.json, output/vue/package.json, package-lock.json, packages/components/package.json
resolves https://github.com/db-ux-design-system/core-web/issues/5108
=> fix: JS framework components packages are missing db-ux dependencies

.github/dependabot.yml
It seems that currently, no PRs grouped by npmjs organisations would be opened, except the patch ones. According to ChatGPT, we should explicitly define the groups in the Dependabot configuration.
=> fix(dependabot): added explicit update types for all dependencies

.github/workflows/00-cancel-workflow.yml, .github/workflows/01-build-patternhub.yml, .github/workflows/01-build-showcases.yml, .github/workflows/default.yml
- cancel-workflow failed because of a missing checkout
- sometimes the `npm` cache don't have the DB assets decrypted, we ensure to decrypt them before building the showcases
=> fix: cancel-workflow and ensure assets are encrypted for showcases
