package.json

so we'd like to make this a "private" "package".

refactor: we won't publish from root

---

package.json

this especially comes in handy in case you need to tidy up your whole folder, but keep your relevant local configurations like currently `.env`.

feat: added clean npm script

---

showcases/react-showcase/src/app.tsx

fix: click event logging text

---

showcases/angular-current-showcase/src/app/app.component.html
showcases/react-showcase/src/app.tsx

Follow up to https://github.com/db-ui/mono/pull/253/

chore: translations

---

packages/foundations/scripts/color-placeholders-generator.js
packages/foundations/scss/_init.scss
packages/foundations/scss/icon/_icons.helpers.scss

move latest base styles (@db-ui/base) to foundations to prepare migration of link component from @db-ui/core

style: update from latest base

---

packages/components/src/components/input/input.scss

fix: input variant style for angular

---

README.md
output/react/README.md
output/vue/vue3/README.md
packages/components/README.md
packages/foundations/README.md
showcases/angular-current-showcase/src/styles.scss
showcases/angular-lts-showcase/src/styles.scss
showcases/next-showcase/styles/globals.scss
showcases/patternhub/styles/globals.scss
showcases/react-showcase/src/index.scss
showcases/reactwind-showcase/src/index.scss
showcases/svelte-showcase/src/index.scss
showcases/vue-showcase/src/index.scss

- It's unclear what the `DB UX System` would be – we should either write `DB UX Design System` if we mean the Design System or add the appendix, if we want to add a link to the technical components part.
- Corrected some path

docs: clarification on the naming

---

.github/workflows/update-prs.yml

We sadly couldn't update our branches programatically at the moment, due to missing results out of https://github.com/orgs/community/discussions/43427.

refactor: we couldn't programmatically update PRs at the moment

---

.github/workflows/default.yml
package-lock.json
packages/components/_templates/mitosis/new/components.ejs.t
packages/components/scripts/post-build/components.js

Fix issues:
- post-script for vue components to satisfy `tsc`
- add `build-ouput` to default cicd to find issues earlier

fix: issues for build-outputs in cicd

---

.markdown-lint.yml
package.json

Errors by `markdownlint` weren't shown on MacOS environments, but could get fixed by quoting the globs.
Fixes https://github.com/db-ui/mono/issues/432

test(markdownlint): doesn't provide correct results

---

packages/components/src/components/input/input.scss
showcases/react-showcase/src/components/input/index.tsx

fix(input): filled icons for inputstate

---

.github/workflows/01-build-power-apps.yml
.github/workflows/03-publish-packages.yml
.github/workflows/default.yml
.github/workflows/release.yml
build-power-apps/package-lock.json
packages/components/src/components/card/card.lite.tsx

closes #439 
Fixed issue with card inside power apps build.
Moved power-apps-build to default pipeline to test it before publish

fix: issue with power apps and test in ci

---

package-lock.json
package.json
packages/components/package.json

fix: moved react-docgen dependency

---

packages/components/_templates/mitosis/new/react-showcase-component.ejs.t
packages/components/_templates/mitosis/new/readme.ejs.t

After creation, both a markdown error comes up and an optimization will get made in the resulting file, so we could make these changes to the sources file already.

refactor: optimizations on generate-components scripts files content

---

.husky/post-checkout
.husky/post-merge
.husky/post-rewrite

It caused to much trouble auto installing dependencies on every branch switch

Removed post hooks (husky)

---

packages/components/src/components/input/input.scss
showcases/react-showcase/src/components/input/index.tsx

- removed styles for pseudo-elements to prepare input web component fix

refactor(input): making input more resilient

---

.github/dependabot.yml

refactor: ignore zone.js minor updates

---

packages/components/scripts/post-build/react.js
packages/components/src/components/radio/radio.lite.tsx

out of https://github.com/db-ui/mono/pull/710
and simplified the code

refactor: added missing attribute

---

showcases/patternhub/pages/_app.tsx

Using the [expected method](https://nextjs.org/docs/basic-features/script) for our use case.

fix: iframe resizer plugin reference

---

showcases/angular-showcase/src/app/app.module.ts
showcases/angular-showcase/src/app/components/link/link.component.html
showcases/angular-showcase/src/app/components/link/link.component.ts
showcases/angular-showcase/src/app/utils/navigation-item.ts
showcases/vue-showcase/src/components/link/Link.vue
showcases/vue-showcase/src/utils/navigation-items.ts

- added link to vue showcase
- added link to angular showcase

docs: add link in missing showcases

---

packages/components/src/components/link/link.scss

- due to changes to foundations we have to update icon size for small links

fix: icon size for variant small

---

showcases/angular-showcase/src/app/app.component.html
showcases/angular-showcase/src/app/components/button/button.component.html
showcases/angular-showcase/src/app/components/default.component.html

Resolves https://github.com/db-ui/mono/issues/820

refactor(angular): switched to hyphen notation

---

packages/components/_templates/mitosis/new/angular-showcase-component-html.ejs.t

refactor: change the notation within the template as well

---

packages/components/src/components/alert/alert.scss
packages/components/src/components/infotext/infotext.scss
packages/components/src/components/input/input.lite.tsx
packages/components/src/components/input/input.scss
packages/components/src/shared/model.ts
packages/foundations/scss/color/_color-variants.scss
packages/foundations/scss/helpers/_component.scss

- Add adaptive variants to foundations 
- Changed Alert, Infotext & Input to use new adaptive variants variable
- Fix issue with double icons for input

refactor: combine adaptive variants to reduce copy paste

---

showcases/patternhub/components/component-parser/data.ts
showcases/patternhub/components/component-parser/index.tsx

Resolves https://github.com/db-ui/mono/issues/876

refactor: added missing entries

---

README.md

chore: add description for versions

---

showcases/shared/divider.json
showcases/shared/drawer.json

Resolves https://github.com/db-ui/mono/issues/1025

chore: simple label corrections

---

packages/components/_templates/mitosis/new/component/tsx.ejs.t
packages/components/src/components/alert/alert.lite.tsx
packages/components/src/components/brand/brand.lite.tsx
packages/components/src/components/button/button.lite.tsx
packages/components/src/components/button/model.ts
packages/components/src/components/card/card.lite.tsx
packages/components/src/components/checkbox/checkbox.lite.tsx
packages/components/src/components/code-docs/code-docs.lite.tsx
packages/components/src/components/divider/divider.lite.tsx
packages/components/src/components/drawer/drawer.lite.tsx
packages/components/src/components/header/header.lite.tsx
packages/components/src/components/icon/icon.lite.tsx
packages/components/src/components/infotext/infotext.lite.tsx
packages/components/src/components/input/input.lite.tsx
packages/components/src/components/link/link.lite.tsx
packages/components/src/components/page/page.lite.tsx
packages/components/src/components/radio/radio.lite.tsx
packages/components/src/components/section/section.lite.tsx
packages/components/src/components/tab-bar/tab-bar.lite.tsx
packages/components/src/components/tab/tab.lite.tsx

- Added `// MS Power Apps` comments to the relevant metadata parts of the component files.
- Solved a simple typo.

chore(docs): necessary changes

---

packages/components/src/components/icon/icon.lite.tsx

Resolves https://github.com/db-ui/mono/issues/1168

feat(icon): added `title` prop

---

build-power-apps/DBUI/DBUI.cdsproj
packages/components/src/components/tag/tag.lite.tsx

- added missing entry to the config file
- added missing import to _tag_
- added missing `children` property to the UI

fix: `tag` build for Power Apps generation

---

build-power-apps/README.md
build-power-apps/alert/DBAlert/strings/DBAlert.de.resx
build-power-apps/brand/DBBrand/strings/DBBrand.de.resx
build-power-apps/button/DBButton/strings/DBButton.de.resx
build-power-apps/card/DBCard/card/DBCard.de.resx
build-power-apps/checkbox/DBCheckbox/strings/DBCheckbox.de.resx
build-power-apps/icon/DBIcon/strings/DBIcon.de.resx
build-power-apps/infotext/DBInfotext/strings/DBInfotext.de.resx
build-power-apps/input/DBInput/strings/DBInput.de.resx
build-power-apps/link/DBLink/strings/DBLink.de.resx
build-power-apps/radio/DBRadio/strings/DBRadio.de.resx
build-power-apps/tag/DBTag/strings/DBTag.de.resx
packages/components/_templates/power-apps/new/comp-xml.ejs.t

Resolves https://github.com/db-ui/mono/issues/1192

feat(power apps): added translations

---

packages/components/_templates/power-apps/new/scss.ejs.t
packages/components/src/components/brand/brand.lite.tsx

Resolves https://github.com/db-ui/mono/issues/1255

refactor(power apps): switch to CDN urls

---

packages/foundations/scripts/color-placeholders-generator.js
packages/foundations/scss/color/_color-variants.scss
packages/foundations/scss/helpers/_component.scss
packages/foundations/tokens/zeplin.json

- default border color changed
- for components we keep old border colors as `border-weak`
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

chore: update border colors (add weak border)

---

.gitignore
build-power-apps/alert/DBAlert/strings/DBAlert.1033.resx
build-power-apps/brand/DBBrand/strings/DBBrand.1033.resx
build-power-apps/button/DBButton/strings/DBButton.1033.resx
build-power-apps/card/DBCard/strings/DBCard.1033.resx
build-power-apps/checkbox/DBCheckbox/strings/DBCheckbox.1033.resx
build-power-apps/icon/DBIcon/strings/DBIcon.1033.resx
build-power-apps/infotext/DBInfotext/strings/DBInfotext.1033.resx
build-power-apps/input/DBInput/strings/DBInput.1033.resx
build-power-apps/link/DBLink/strings/DBLink.1033.resx
build-power-apps/radio/DBRadio/strings/DBRadio.1033.resx
build-power-apps/tag/DBTag/strings/DBTag.1033.resx
packages/components/_templates/power-apps/new/comp-xml.ejs.t

Resolves https://github.com/db-ui/mono/issues/1312

refactor(power apps): added english language files

---

packages/components/_templates/power-apps/new/comp-xml.ejs.t

Previous to resolving issue https://github.com/db-ui/mono/issues/1105 we'd like to add the current list to the file manually.

refactor(power apps): added further icons to the list

---

packages/components/_templates/power-apps/new/comp-xml.ejs.t

hyphen instead of underscore for the moment
Resolves https://github.com/db-ui/mono/issues/1336

fix(power apps): corrected the naming convention

---

.lintstagedrc

Resolves https://github.com/db-ui/mono/issues/1309

refactor(lint-staged): ignoring unknown file extensions on prettifying staged files

---

packages/components/scripts/post-build/components.js
packages/components/src/components/textarea/textarea.lite.tsx
showcases/patternhub/components/component-parser/index.tsx

Adapted some code out of a newly generated component.

refactor(textarea): optimized current component implementation

---

packages/components/scripts/post-build/components.js
packages/components/src/components/textarea/textarea.lite.tsx
showcases/patternhub/components/component-parser/index.tsx

Revert "refactor(textarea): optimized current component implementation"

---

packages/components/src/components/drawer/docs/HTML.md
packages/components/src/components/drawer/index.html

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

chore: aligned attribute with MDN documentation

---

.husky/pre-commit
.lintstagedrc

Resolves https://github.com/db-ui/mono/issues/1424

refactor: consolidate lintings on pre commit

---

packages/components/src/components/alert/alert.lite.tsx
packages/components/src/components/infotext/infotext.lite.tsx
packages/components/src/components/input/input.lite.tsx
packages/components/src/components/link/link.lite.tsx
packages/components/src/components/tag/tag.lite.tsx

Resolves https://github.com/db-ui/mono/issues/1470

refactor(Power Apps): added correct default component values

---

packages/foundations/scss/_tonality.scss

Power-Apps loading a MS font for db-components....

fix: db font-family for power apps

---

packages/components/src/components/header/header.lite.tsx
packages/components/src/components/header/header.scss

Fix issues with mobile header:
- empty meta-navigation was displayed
- drawer-content had spacing

fix: issues with mobile header

---

packages/foundations/tokens/tailwind/spacing.json

Fix: Missing sizes and wrong css-prop for tailwind

fix: issue with tailwind sizings

---

packages/components/src/components/input/input.lite.tsx
packages/components/src/components/input/model.ts

- Add missing types for input
- Add step for input types with date/time

fix: missing input types

---

build-power-apps/DBUI/DBUI.cdsproj
packages/components/src/components/divider/divider.lite.tsx

The divider components needs to get deactivated again for the moment, as it doesn't work as expected. And we need to provide some default values for future usage.

refactor(Power Apps): divider

---

packages/components/_templates/power-apps/new/comp-xml.ejs.t

Resolves https://github.com/db-ui/mono/issues/1514

refactor: changed syntax

---

packages/foundations/scss/_tonality.scss

Resolves https://github.com/db-ui/mono/issues/1524

fix(power apps): added missing selector for font-family definition

---

package.json

The old script was outdated and needed an update

test: 💍 updated script for screenshot regeneration

---

docs/how-to-develop-a-component.md
packages/components/src/styles/_form-components.scss

fix: new icons syntax

---

packages/components/src/components/infotext/infotext.lite.tsx

Resolves https://github.com/db-ui/mono/issues/1528

fix: infotext component text breaks unnecessarily

---

packages/components/src/components/link/link.scss
packages/foundations/scss/db-ui-foundations.scss
packages/foundations/scss/helpers/_component.scss

Changing the colors to dark mode had a wired transition error, because of the stacking of the transitions for db-components.

fix: issue with transition for foreground color

---

packages/components/src/components/checkbox/checkbox.lite.tsx
packages/components/src/shared/model.ts
showcases/angular-showcase/src/app/components/form/form.component.html
showcases/react-showcase/src/components/form/index.tsx

Support for the HTML defaultChecked property for <input> types checkbox and radio.

feat: :sparkles: add optional prop defaultValue

---

packages/components/src/components/tag/tag.scss

fix: issue with interactive tags

---

packages/components/src/components/textarea/textarea.lite.tsx

The `textarea` component should have a controlled `height` and width.

refactor(textarea): power apps component should have `controlled` height

---

packages/components/index.html
packages/components/src/components/main-navigation/main-navigation.scss
packages/components/src/icons.html
packages/foundations/scss/icon/_icon-helpers.scss
packages/foundations/scss/icon/icons.scss

`data-icon-after` did not work properly

fix: issue with wrong data-icon-after

---

packages/foundations/tokens/tailwind/spacing.json

It's common to use `0` for a lot of spacings in tailwind e.g. `inset-0`, this wasn't possible

fix: issue with missing 0 spacing for tailwind

---

packages/foundations/package.json

fix: issue with missing copy for foundation scripts

---

packages/components/src/components/popover/popover.spec.tsx
packages/components/src/components/tooltip/tooltip.scss
packages/components/src/components/tooltip/tooltip.spec.tsx
packages/components/src/shared/model.ts
packages/components/src/styles/_popover-component.scss
showcases/shared/popover.json
showcases/shared/tooltip.json

Add additional placements for popover and tooltip.

feat: add additional popover placements

---

packages/components/src/components/radio/radio.scss

fix: wrong radio button color

---

packages/components/src/components/tooltip/tooltip.scss
packages/components/src/styles/_popover-component.scss

Fix popover elevation

---

packages/components/src/components/accordion-item/accordion-item.scss
packages/foundations/scss/animation/_animations.scss

fix: explicit styling for accordion content spacing

---

packages/foundations/scss/_variables.scss

Resolves https://github.com/db-ui/mono/issues/1795

chore(docs): corrected comment

---

packages/foundations/scss/_init.scss

chore: removed unused css-property

---

packages/foundations/scss/colors/_default-color-scheme.scss
packages/foundations/scss/colors/color-scheme.scss

- fix overwriting color scheme by data-color-scheme attribute
- added color-scheme prop to adopt native browser styles in different color schemes

style: 💄 fix overwrites for color scheme

---

packages/foundations/scripts/generate-icon-fonts/index.js

Make icon font generation file executable

fix: make icon generation *.js file executable

---

.github/dependabot.yml

fix: add major version to ignore pattern for react and angular

---

packages/components/src/components/accordion/accordion.lite.tsx
showcases/react-showcase/src/components/form/index.tsx

fix: issue with accordion when items are populated later

---

.github/labeler.yml

chore: update labeler to use emojis

---

README.md

- Removed an obsolete content block.
- Corrected _CODE OF CONDUCT_ and _Contributing_ URLs.

docs(README): necessary corrections

---

README.md

docs(README): changed further aspects

---

packages/components/src/components/accordion-item/accordion-item.scss

chore(scss): further simplification

---

packages/foundations/scripts/generate-icon-fonts/gather-icons.js

Resolves https://github.com/db-ui/mono/issues/1921

fix: icon generation process error messages

---

packages/components/src/components/header/header.lite.tsx
packages/components/src/components/header/header.scss
packages/foundations/scss/_screen-sizes.scss

closes #1917
- rename `force-mobile` to `data-force-mobile`
- caused issue by some CSS build tools

refactor: rename `force-mobile` to `data-force-mobile`

---

showcases/react-showcase/vite.config.ts
showcases/vue-showcase/vite.config.ts

fix: issue with missing logo

---

packages/foundations/assets/icons/README.md

README.md update with some general information about the package and change of modifications

docs(icons): Update README.md

---

packages/components/scripts/post-build/components.js
packages/components/scripts/post-build/react.js
packages/components/src/shared/model.ts
packages/components/src/utils/index.ts

fix: issue with duplicated event for drawer in react

---

packages/components/src/components/tag/tag.scss

chore(tags): removed obsolete declaration

---

.github/scripts/release/index.js
.github/scripts/release/upload-asset.js

- fix issue with uploading assets, [oktakit](https://octokit.github.io/rest.js/v20) wraps everything in `data`

fix: asset upload

---

.github/scripts/cleanup-gh-pages.js

fix: clean-up issue for gh-pages

---

packages/components/src/components/input/input.lite.tsx
packages/components/src/components/select/select.lite.tsx
packages/components/src/components/textarea/textarea.lite.tsx
packages/components/src/shared/model.ts
packages/components/src/styles/_form-components.scss
showcases/patternhub/components/index.tsx

feat: add autocomplete and caret-color for form elements

---

packages/components/src/components/header/header.lite.tsx
packages/components/src/components/header/header.scss

refactor: removed data-hide-on for header

---

.github/workflows/00-scan-secrets.yml

fix: issue with truffle hog on main

---

packages/foundations/scss/animation/_transitions.scss

fix: issue with duplicated transition variables

---

packages/components/src/components/icon/icon.lite.tsx
packages/components/src/components/icon/model.ts

feat: add variant and weight props to DBIcon

---

.github/labeler.yml

the new version of [labeler](https://github.com/actions/labeler) required some changes for the config

fix: issue with new labeler version

---

docs/research-other-design-systems.md
docs/scripts/component-research/design-systems.js

Adding W3C accessibility related & inspired patterns.

docs: update inspirational websites

---

packages/components/src/components/header/header.scss

fix(rollup): corrected selector nesting

---

.github/scripts/update-playwright.js

fix: issue with update-playwright.js

---

docs/research-other-design-systems.md

Update the Storybook URL for the Lyne Design System from SBB.
Hello there 😃 
We noticed our design system(s) being referenced.
Would you be interested in a short exchange about our/your experiences?

docs: update SBB Storybook link

---

.github/workflows/02-e2e-showcases.yml
.github/workflows/02-e2e.yml

Resolves https://github.com/db-ui/mono/issues/2149

fix: actions/upload-artifact naming convention

---

.github/scripts/update-playwright.js
.github/workflows/02-e2e-showcases.yml
.github/workflows/02-e2e.yml
e2e/Dockerfile
e2e/package-lock.json
e2e/package.json

we needed to update playwright in the missing places as well as within the `oldPlaywrightVersion` string.

refactor: updated playwright

---

packages/components/scripts/post-build/react.js

fix: issue with react forward ref

---

.github/workflows/99-update-playwright.yml

fix: issues with playwright update

---

packages/components/_templates/mitosis/new/readmes/readme-angular.ejs.t
packages/components/_templates/update-docs/new/readme-angular.ejs.t
packages/components/src/components/accordion-item/docs/Angular.md
packages/components/src/components/accordion/docs/Angular.md
packages/components/src/components/alert/docs/Angular.md
packages/components/src/components/badge/docs/Angular.md
packages/components/src/components/brand/docs/Angular.md
packages/components/src/components/button/docs/Angular.md
packages/components/src/components/checkbox/docs/Angular.md
packages/components/src/components/divider/docs/Angular.md
packages/components/src/components/drawer/docs/Angular.md
packages/components/src/components/icon/docs/Angular.md
packages/components/src/components/infotext/docs/Angular.md
packages/components/src/components/link/docs/Angular.md
packages/components/src/components/main-navigation/docs/Angular.md
packages/components/src/components/popover/docs/Angular.md
packages/components/src/components/radio/docs/Angular.md
packages/components/src/components/section/docs/Angular.md
packages/components/src/components/select/docs/Angular.md
packages/components/src/components/tag/docs/Angular.md
packages/components/src/components/textarea/docs/Angular.md
packages/components/src/components/tooltip/docs/Angular.md

docs(ngx-components): describe how to use with standalone components

---

packages/components/src/components/checkbox/docs/Angular.md
packages/components/src/components/radio/docs/Angular.md

docs(angular): use new control flow syntax

---

packages/components/src/components/button/button.scss

fix: remove text-decoration for db-button to use <a> tag

---

package-lock.json
package.json

chore: revert broken commitlint dependency

---

.vscode/extensions.json

refactor: added recommendation for `stylelint` VS Code extension

---

.vscode/settings.json

refactor: added relevant VS Code setting for default linter

---

packages/components/scripts/post-build/components.js
packages/components/src/components/accordion-item/accordion-item.lite.tsx
packages/components/src/components/accordion-item/model.ts
showcases/angular-showcase/src/app/components/accordion-item/accordion-item.component.html
showcases/angular-showcase/src/app/components/accordion-item/accordion-item.component.ts
showcases/react-showcase/src/components/accordion-item/index.tsx
showcases/vue-showcase/src/components/accordion-item/AccordionItem.vue

The accordion-item didn't work as expected. This fix will handle the `open` state correctly

fix: broken accordion

---

.github/workflows/release.yml

fix: typo for pipeline

---

package-lock.json
packages/foundations/package.json

we should pin all `dependencies`.

refactor: pin `dependencies`

---

showcases/react-showcase/src/components/input/index.tsx

fix: issue with defaultValue for input floating label

---

README.md

docs: removed component list to reduce maintenance

---

packages/components/docs/getting-started.md

We shouldn't promote [`node-sass`](https://npmjs.com/node-sass) any further, as it's a deprecated package.

chore(docs): removed obsolete part

---

packages/components/src/components/accordion-item/accordion-item.lite.tsx

- `DBAccordion` `behaviour="single"` was broken, because `accordion-item` had no id

fix: issue with accordion with single behaviour

---

packages/foundations/scss/colors/_variants.scss

fix: wrong focus outline offset

---

showcases/patternhub/data/routes.ts

docs: hide icon and page from patternhub

---

showcases/patternhub/pages/_document.tsx

Fixes https://github.com/db-ui/mono/issues/2371

refactor: added missing title

---

.github/actions/npm-cache/action.yml

chore: update cache action for workflows

---

output/vue/vue3/package.json

Adds path to type definitions to exports in package.json.

fix: adds types to exports in package.json

---

output/angular/README.md
packages/components/src/components/header/docs/Angular.md

docs: add information for angular output hash issue

---

packages/foundations/README.md

fix: links with foundation readme

---

showcases/patternhub/components/default-page.tsx

caused by [highlightjs](https://github.com/highlightjs/highlight.js/issues/4013)
closes #2409

fix: issue with properties page for patternhub

---

packages/components/src/styles/_popover-component.scss

fix: issue with wrong tooltip distance

---

output/angular/README.md
output/react/README.md
output/vue/vue3/README.md
packages/components/src/components/textarea/docs/Angular.md
packages/components/src/components/textarea/docs/React.md
packages/components/src/components/textarea/docs/Vue.md

docs: refactored wrong description prop for textarea
closes #2439
closes #2440

docs: removed custom events from Readmes

---

packages/components/src/components/drawer/docs/Vue.md

Fixes https://github.com/db-ui/mono/issues/2437

docs: missing value to set openDrawer ref

---

packages/components/src/components/navigation/docs/Vue.md

docs: vue navigation-item wraps each router-link

---

.github/dependabot.yml

The mitosis group entry currently did only work for one package, because we were missing the asterisk.

refactor(dependabot): optimized mitosis selector

---

packages/foundations/scss/_font-faces.scss

fix: removes local sources for font faces

---

packages/components/src/components/navigation/navigation.scss

fix: adds show pulse to navigation item on root level

---

showcases/patternhub/scripts/get-code-files.js

fix: issue with copy button using wrong icon

---

showcases/patternhub/scripts/get-code-files.js

refactor: optimized for meaningful description

---

packages/foundations/nodemon.json
packages/foundations/package.json

Resolves https://github.com/db-ui/mono/issues/2568

fix: local `dev` script is constantly going round in circles

---

packages/components/src/components/drawer/model.ts
packages/components/src/styles/_dialog-init.scss
showcases/patternhub/styles/globals.scss
showcases/shared/drawer.json

feat: add invisible variant for drawer

---

README.md

documentation update regarding one simple, but prominent leftover.

chore(docs): alpha to beta leftover

---

showcases/patternhub/pages/foundations/colors/color-schemes.tsx

fixes icon in: https://db-ui.github.io/mono/review/main/foundations/colors/color-schemes

docs: change wrong icon for night/day

---

packages/components/scripts/post-build/vue.js

`v-model` currently not working because of wrong replacement path

fix: issue with v-model

---

packages/components/src/styles/db-ui-components.scss

chore: simplification

---

packages/components/src/components/page/page.lite.tsx
packages/components/src/components/page/page.scss
showcases/patternhub/.gitignore
showcases/patternhub/components/old-routing-fallback/index.tsx
showcases/patternhub/scripts/generate-docs-mdx.js
showcases/patternhub/styles/globals.scss

[Marketingportal](https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/db-ux-design-system/version-3/components/action/button) cannot load properties page in `iframe`.

fix: issue for patternhub included inside iframe

---

showcases/patternhub/scripts/generate-docs-mdx.js

fix: issue for marketingportal and overview pages

---

packages/components/src/components/accordion-item/docs/HTML.md
packages/components/src/components/accordion/docs/HTML.md
packages/components/src/components/header/docs/HTML.md
packages/components/src/components/radio/docs/HTML.md

docs: update HTML.md files to remove unused ids

---

packages/components/src/styles/dialog-init.scss

fix: issue with backdrop color

---

output/angular/README.md
output/react/README.md
output/vue/README.md

added relevant links to the documentation; would need a release afterwards

chore(docs): added links

---

packages/foundations/README.md
packages/foundations/tailwind/tailwind-tokens.json

docs: update foundations README.md for tailwind.config use with TS

---

packages/components/src/components/header/docs/HTML.md

chore: code formatting

---

.github/scripts/build-gh-page.sh

chore: added further logging

---

.github/dependabot.yml
output/react/package.json
output/vue/package.json
package-lock.json
packages/components/package.json
packages/foundations/package.json
showcases/patternhub/package.json

This is a quick fix, we need to investigate why this [version](https://github.com/sass/dart-sass/compare/1.77.4...1.77.5) increases building time so much.

fix: pin sass dependency, 'build' was too slow with version > 1.77.4

---

CODEOWNERS
packages/foundations/docs/Colors.md
packages/foundations/scss/colors/_default-color-scheme.scss
packages/foundations/scss/default-theme.scss
packages/foundations/scss/init/default-fonts.scss

Fixes https://github.com/db-ui/mono/issues/2776

refactor: optimizing scss code

---

.github/workflows/01-build-showcases.yml

Resolves https://github.com/db-ui/mono/issues/2794

refactor: npx shouldn't install `tsx` independently from our version

---

packages/components/src/components/tag/tag.scss

fix: issue with removable tag closing button height

---

.github/actions/extract-branch/action.yml

Resolve https://github.com/db-ui/mono/issues/2836

refactor: update actions/github-script to the latest version

---

.github/workflows/release.yml

Resolves https://github.com/db-ui/mono/issues/2841

fix(ci/cd): missing declarations

---

.github/workflows/release.yml

fix: issue with patternhub release build

---

packages/components/src/components/accordion-item/accordion-item.lite.tsx
packages/components/src/components/accordion/accordion.lite.tsx

chore: removed leftovers

---

packages/components/src/components/tabs/tabs.lite.tsx
showcases/react-showcase/src/components/form/index.tsx
showcases/vanilla-showcase/src/app-shell.js

chore: code simplifications

---

packages/components/src/components/input/input.scss

`variant=hidden` for `DBInput` isn't working correctly with additional icon

fix: issue with hidden label for input datalist icon

---

.lintstagedrc.js

config `.lintstagedrc.js` optimization

chore: config `.lintstagedrc.js` optimization

---

CODE-OF-CONDUCT.md

refactor: Update `CODE-OF-CONDUCT.md`

---

showcases/patternhub/scripts/get-code-files.js

Resolves https://github.com/db-ui/mono/issues/2963

fix: docs URL

---

showcases/patternhub/styles/globals.scss

docs: change size of show code to increase readability

---

packages/foundations/docs/Colors.md
packages/foundations/scss/colors/classes/_get-class.scss
showcases/patternhub/components/foundations/colors/data.ts
showcases/patternhub/data/routes.tsx
showcases/patternhub/pages/foundations/colors/color-classes.tsx
showcases/patternhub/pages/foundations/colors/color-usage-guide.tsx

align color docs to color update

docs: align color docs to color update

---

packages/foundations/tailwind/tailwind-tokens.json

Nested fontsize for tailwind didn't work

fix: issue with nested tailwind tokens not working for fontsize

---

showcases/screen-reader/tests/button.spec.ts
showcases/screen-reader/tests/input.spec.ts
showcases/screen-reader/tests/radio.spec.ts

chore(docs): added brackets

---

packages/components/src/components/select/select.scss

fix: issue with select option for windows

---

docs/how-to-develop-a-component.md
showcases/patternhub/pages/foundations/test-table/index.tsx

refactor(docs): wording

---

packages/components/src/components/checkbox/checkbox.scss
packages/components/src/components/switch/switch.scss
packages/components/src/styles/_form-components.scss

With the color update, some variables were wrong
DBUXDS-3208

fix: wrong variables for radio, checkbox and switch

---

showcases/angular-showcase/src/app/components/brand/brand.component.html
showcases/angular-showcase/src/app/components/notification/notification.component.html
showcases/react-showcase/src/components/brand/index.tsx
showcases/react-showcase/src/components/notification/index.tsx
showcases/vue-showcase/src/components/brand/Brand.vue
showcases/vue-showcase/src/components/notification/Notification.vue

Resolves https://github.com/db-ui/mono/issues/3035
This came actually out of findings within https://github.com/db-ui/mono/pull/3007

fix(showcases): ensure a minimum of words in alternative texts

---

showcases/shared/navigation-item.json
showcases/shared/navigation.json

docs: add correct show code for navigation

---

README.md

added missing information and links towards our migration documentation.

docs: add migration guide

---

packages/foundations/scss/icons/_icon-helpers.scss

this declaration was mainly related to a [bug in older versions of Safari](https://github.com/db-ui/core/pull/766), that doesn't occur anymore.

refactor: simplification

---

packages/foundations/assets/icons/README.md

docs: corrected path

---

packages/foundations/docs/CustomIcons.md

added some part for clarity, as the current path might be misleading.

docs: clarity

---

package-lock.json
packages/foundations/package.json

ensure that this dependency is somehow "defined" and even also installed instead of fetched for npx

refactor: "preinstall" dev dependency

---

.github/workflows/02-e2e-screen-reader.yml

Increase screen-reader tests shards for playwright to fasten pipeline

chore: increase shards for screen reader tests

---

output/vue/scripts/fix-any-types.ts

fix: issue vue tsc

---

packages/components/src/components/link/link.scss
packages/components/src/styles/_link-components.scss
showcases/react-showcase/src/components/form/index.tsx

fix: issue with long inline links not breaking

---

docs/migration/v0.2.x-to-v0.3.x.md
docs/migration/v0.3.x-to-v0.4.x.md

Resolves https://github.com/db-ui/mono/issues/3260 & https://github.com/db-ui/mono/issues/3259

docs(migration): pin foundations version

---

packages/components/_templates/mitosis/new/component/spec.ejs.t
packages/components/src/components/accordion-item/accordion-item.spec.tsx
packages/components/src/components/accordion/accordion.spec.tsx
packages/components/src/components/badge/badge.spec.tsx
packages/components/src/components/brand/brand.spec.tsx
packages/components/src/components/button/button.spec.tsx
packages/components/src/components/card/card.spec.tsx
packages/components/src/components/checkbox/checkbox.spec.tsx
packages/components/src/components/divider/divider.spec.tsx
packages/components/src/components/infotext/infotext.spec.tsx
packages/components/src/components/input/input.spec.tsx
packages/components/src/components/navigation-item/navigation-item.spec.tsx
packages/components/src/components/notification/notification.spec.tsx
packages/components/src/components/popover/popover.spec.tsx
packages/components/src/components/radio/radio.spec.tsx
packages/components/src/components/select/select.spec.tsx
packages/components/src/components/switch/switch.spec.tsx
packages/components/src/components/tabs/tabs.spec.tsx
packages/components/src/components/tag/tag.spec.tsx
packages/components/src/components/textarea/textarea.spec.tsx
packages/components/src/components/tooltip/tooltip.spec.tsx

chore: import declaration optimization

---

.github/scripts/build-gh-page.sh

Resolves https://github.com/db-ui/mono/issues/3290

refactor: embed our page into an iframe instead of doing a redirect

---

.github/dependabot.yml

refactor(dependabot): added new dependency that needs grouping

---

showcases/patternhub/pages/foundations/test-table/index.tsx
showcases/shared/_accessibility-review.json

* `drawer` has been fixed with https://github.com/db-ui/mono/issues/2035
* `button` has been fixed with https://github.com/db-ui/mono/issues/2036
* `radio` and `checkbox` have been fixed with https://github.com/db-ui/mono/issues/2037

docs: updated accessibility test status

---

showcases/angular-showcase/src/app/components/section/section.component.html

chore: corrected attribute

---

packages/components/src/components/drawer/drawer.spec.tsx

by [JavaScript and TypeScript Organize Imports](https://code.visualstudio.com/updates/v1_23#_javascript-and-typescript-organize-imports)

chore: optimize imports

---

showcases/angular-showcase/README.md

refactor: slight optimizations

---

README.md

fix: correct dimensions

---

README.md

docs: adding new migration documentation

---

packages/foundations/README.md

fix(docs): corrected URLs

---

packages/components/README.md

Resolves https://github.com/db-ui/mono/issues/3350

fix(docs): corrected URL

---

.github/scripts/build-gh-page.sh

fix: issue with gh-pages latest site

---

packages/components/src/utils/navigation.ts

fix: slow save triangle for navigation

---

.github/scripts/cleanup-gh-pages.js

Resolves https://github.com/db-ui/mono/issues/3407

refactor: let's not cleanup the `latest` folder

---

.github/dependabot.yml

There was the wrong version ignore for `eslint` inside `dependabot.yml`

fix: issue with dependabot updating eslint major version

---

packages/foundations/docs/IDESupport.md

fix(docs): corrected that path

---

showcases/patternhub/components/version-switcher/version-switcher.tsx

Resolves https://github.com/db-ui/mono/issues/3410

fix: `latest` is a "version"

---

packages/foundations/ide/db.ide.css

Missed `-basic` word for emphasis colors in `ide.css`

fix: issue with wrong variable names for ide support

---

showcases/patternhub/pages/foundations/variables/examples.tsx

fix: icon got renamed

---

CONTRIBUTING.md
docs/conventions.md
package.json

fix(docs): urls and content

---

showcases/patternhub/styles/globals.scss

Disable auto dark-mode for Marketingportal iframes

docs: disable auto-dark mode for iframes

---

showcases/e2e/tabs/tabs-snapshot.spec.ts

Pipelines are failing for `vue-showcase` if the `Scroll Right` button isn't visible at the time the snapshot has been created.

fix: issue with flaky tabs aria-snapshot for vue showcase

---

packages/components/scripts/post-build/components.ts
packages/components/src/components/accordion-item/model.ts
packages/components/src/components/drawer/model.ts
packages/components/src/components/header/model.ts
packages/components/src/components/navigation-item/model.ts
packages/components/src/components/navigation-item/navigation-item.lite.tsx
packages/components/src/components/notification/model.ts
packages/components/src/components/page/model.ts
packages/components/src/components/popover/model.ts

refactor: `@types/react` changes

---

packages/components/src/utils/index.ts

refactor: code optimizations

---

docs/research-other-design-systems.md

docs: added new entry for a design system

---

docs/migration/v0.5.x-to-v0.6.x.md

docs: added relevant migration section

---

packages/components/src/styles/_component.scss

This reverts commit 83498c0edf43a727d18e50c6f8c331cb8e24ae8e.

Revert "Update _component.scss (#3562)"

---

docs/research/footer.md

chore: prettier

---

showcases/patternhub/styles/globals.scss

refactor(css): semantic declarations

---

README.md
docs/package.json
packages/components/package.json
packages/foundations/package.json

docs: added DST version

---

packages/components/src/components/header/docs/HTML.md
packages/components/test/import-styles/simple-button/index.html
showcases/angular-showcase/src/app/app.component.html
showcases/angular-showcase/src/app/components/form/form.component.html
showcases/angular-showcase/src/app/components/header/header.component.html
showcases/nuxt-showcase/layouts/default.vue
showcases/vue-showcase/src/App.vue
showcases/vue-showcase/src/components/badge/Badge.vue
showcases/vue-showcase/src/components/header/Header.vue

refactor: prettier

---

showcases/patternhub/pages/foundations/icons/overview.tsx

fix: issue with icon overview not using DB core icons

---

packages/foundations/scripts/local/generate-icon-types.ts

fix: generate-icon-types.ts to use proper .js ending

---

packages/components/README.md

docs: added Web Components to the listing

---

.github/workflows/02-e2e-screen-reader.yml
showcases/react-showcase/package.json

Test cicd sr playwright shard

---

packages/components/src/components/tabs/index.html

refactor: prettification

---

packages/foundations/docs/CustomIcons.md
packages/foundations/docs/Icons.md

docs: update docs for icon autocomplete

---

packages/components/src/styles/internal/_popover-component.scss
scripts/package.json
showcases/react-showcase/src/components/form/index.tsx

fix: z-index for popover and tooltip to appear above other elements

---

showcases/patternhub/pages/foundations/icons/overview.tsx

fix: icon overview for patternhub

---

packages/components/scripts/post-build/components.ts

fix: issue with angular input type=date resetting by using "0"

---

README.md

docs: update README.md with migration links

---

showcases/patternhub/pages/foundations/test-table/index.tsx
showcases/patternhub/scripts/generate-test-table.js

docs: include aria snapshots in testing table

---

README.md
output/angular/README.md
output/react/README.md
output/stencil/README.md
output/vue/README.md
packages/components/README.md
packages/foundations/README.md
packages/migration/README.md

We need to optimize our documentation section on how to consume and integrate especially the styling related parts.

docs: optimizations regarding consumption and integration

---

README.md
docs/development.md

docs: added development documentation

---

showcases/shared/_accessibility-review.json

to reflect latest test results

docs: update _accessibility-review.json

---

README.md

chore(docs): small optimization

---

output/angular/README.md
output/react/README.md
output/stencil/README.md
output/vue/README.md
packages/components/README.md
packages/foundations/README.md
packages/migration/README.md

chore(docs): corrected copy

---

packages/foundations/docs/Colors.md

docs: corrected the definition for full page dark/light mode overwrites

---

docs/package.json
output/angular/package.json
output/react/package.json
output/stencil/package.json
output/vue/package.json
package.json
packages/components/package.json
packages/foundations/package.json
packages/migration/package.json
packages/stylelint/package.json

refactor: adding relevant prefix

---

.github/dependabot.yml

refactor: dependabot updates timing

---

README.md
output/angular/README.md
output/react/README.md
output/stencil/custom-elements-manifest.config.js
output/vue/README.md
package.json
packages/components/docs/router-usage.md
packages/components/src/components/header/docs/HTML.md
packages/components/src/shared/model.ts
packages/foundations/README.md
packages/foundations/docs/Densities.md
showcases/patternhub/scripts/get-properties-file.js

refactor: adapted the custom domain

---

packages/components/src/components/page/model.ts
packages/components/src/components/page/page.lite.tsx

feat: add mainClass to DBPage

---

packages/components/src/components/radio/docs/HTML.md

Resolves https://github.com/db-ux-design-system/core-web/issues/3960

fix(docs): corrected declaration

---

.vscode/settings.json

Added `.env.template` file type definition for VS Code.

chore(vscode): added filetype definition

---

docs/development.md

docs: enhanced description for snapshot updates

---

showcases/angular-showcase/src/app/components/form/form.component.html

Corrected attributes / property names

refactor: corrected attributes

---

showcases/angular-showcase/src/app/components/tooltip/tooltip.component.html

Removed an obsolete attribute, that's not included in the schema.

refactor: removed obsolete attribute

---

packages/foundations/docs/CustomIcons.md

- updates docs to correct link for icon font generation

docs: update link to icon font tool after renaming

---

package-lock.json
package.json

chore: updated db theme package

---

e2e/package.json
output/react/package.json
output/vue/package.json
package-lock.json
package.json

chore: update playwright

---

README.md

chore(docs): naming

---

packages/foundations/scss/icons/_icon-helpers.scss

refactor(icons): enabled Firefox lower version 128 support again

---

packages/components/scripts/post-build/components.ts

fix: issue with select for angular not using initial value

---

packages/foundations/package.json

We used the old custom licence which we've replaced by Apache-2.0

chore: update foundation licence to Apache-2.0

---

package-lock.json

package lock file hasn't been updated with https://github.com/db-ux-design-system/core-web/pull/4137

refactor: necessary changes to package lock file

---

.prettierrc.json
package-lock.json
package.json

chore: remove prettier (`prettier-plugin-sh`) plugin

---

packages/foundations/tailwind/theme/index.css
packages/foundations/tailwind/theme/revert-theme.css

before committing stylelint throws an error

fix: stylelint issues

---

packages/foundations/scss/helpers/_focus.scss

Solves https://github.com/db-ux-design-system/core-web/issues/4175

fix: corrected focus outline color

---

packages/components/src/components/accordion-item/accordion-item.scss
packages/components/src/components/custom-select-list-item/custom-select-list-item.scss
packages/components/src/components/select/model.ts
showcases/shared/custom-select.json

fix: additional custom select issues

---

.env.template
CONTRIBUTING.md

docs: update contribution notes

---

docs/release-management.md

We should align a process and responsibilities regarding release management.

docs: how to release

---

docs/release-management.md

docs: linting issues for release-management.md

---

package-lock.json
package.json

feat: updated DB UX Theme

---

.github/workflows/02-e2e-screen-reader.yml

chore: add guidepup setup retry

---

.config/lint-staged-prettier.config.ts
.config/lint-staged.config.ts
.husky/pre-commit

chore: update lint-staged config

---

.stylelintrc.json
docs/how-to-develop-a-component.md
docs/research/table.md
package-lock.json
package.json
packages/components/src/components/drawer/model.ts
packages/components/src/components/input/input.scss
packages/components/src/components/navigation/navigation.scss
packages/components/src/components/tag/tag.scss
packages/components/src/styles/internal/_form-components.scss
packages/foundations/scss/_screen-sizes.scss
packages/foundations/scss/defaults/default-required.scss
packages/foundations/scss/icons/_icon-helpers.scss

chore: update to stylelint-config-recommended-scss

---

packages/components/src/components/button/button.scss

fix: issue with button `variant=""`

---

.config/.lintstagedrc-prettier.js
.config/.lintstagedrc.js

Adding JSDoc comments in the `lint-staged` config file again, that has been introduced with version 15.4.0: https://github.com/lint-staged/lint-staged/blob/main/CHANGELOG.md#1540

docs(`lint-staged`): added JSDoc config file

---

.config/.lintstagedrc.js

as the other linting / codestyle tools like `prettier` and `stylelint` are even also processed to fixing the problems right away, we should active this as well for markdownlint.

refactor: aligned lint fixing

---

packages/components/src/components/custom-select/custom-select.scss

Resolves https://github.com/db-ux-design-system/core-web/issues/4377

fix(DBCustomSelect): placeholder colliding with selected value

---

docs/package.json

chore: mark docs "package" as private

---

packages/components/package.json
showcases/react-showcase/vite.config.ts
showcases/vue-showcase/vite.config.ts

For localhost debugging we'd like to know which SASS file includes the CSS declarations from Web Dev tools.

feat: provide SASS sourcemaps

---

.github/actions/auto-commit/action.yml

If we retrieve the key after we're already set up the PR, any problems during this retrieval and the automated approval and auto-merge settings wouldn't harm creating the PR.

refactor(action): auto-commit resilience

---

package-lock.json

refactor: npm audit fix

---

.github/workflows/00-scan-secrets.yml
README.md

According to trufflehogs documentation, to scan an entire branch, it's only necessary to provide some simple configuration:
https://github.com/marketplace/actions/trufflehog-oss#advanced-usage-scan-entire-branch

fix: trufflehog

---

packages/foundations/docs/BrowserSupport.md

`style()` container queries are even also on the edge of being supported by all evergreen browsers.

docs: added another browsersupports feature

---

packages/foundations/docs/BrowserSupport.md

Safari has added an implementation of `hidden="until-found"` lately.

docs: another browser version support update

---

package.json
scripts/check-docs.js

Due to several included file references in our documentation to old filenames or path we'd like to test for any file references in our documentation whether they correctly resolve to a file.

test: checking for false file references in our docs

---

packages/components/src/components/select/select.lite.tsx

chore: removed a leftover

---

.config/.lintstagedrc.js
showcases/patternhub/scripts/utils.js

Resolves https://github.com/db-ux-design-system/core-web/issues/4712

refactor: we shouldn't output the name into the innerContent in general

---

.husky/pre-push

We could exclude several folders from `grep`.

refactor: optimized `pre-push` script

---

showcases/patternhub/scripts/utils.js

This reverts additionally reverts the solution out of commit 0279666c98a36965a4e1a87c4ee8d72a41cebfa1.

fix(docs): not setting innercontent for composition components

---

showcases/shared/_accessibility-review.json

Added successful accessibility test to testing table.

docs: added a11y review entry for "switch" component

---

.changeset/eleven-balloons-whisper.md
.changeset/modern-doors-give.md
.changeset/old-wings-appear.md
.changeset/plenty-adults-unite.md

Removed the released changesets.

refactor: removed older changesets

---

.changeset/chatty-jobs-tell.md
.changeset/refactor-enable-hidden.md
output/angular/CHANGELOG.md
output/angular/package.json
output/react/CHANGELOG.md
output/react/package.json
output/stencil/CHANGELOG.md
output/stencil/package.json
output/vue/CHANGELOG.md
output/vue/package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/foundations/CHANGELOG.md
packages/foundations/package.json
packages/migration/CHANGELOG.md
packages/migration/package.json
packages/stylelint/CHANGELOG.md
packages/stylelint/package.json

This reverts commit fc8b1602e32f9f6b9b1a50b187b123e0f612dbac.

Revert "chore(release): version packages (#5129)"

---

.github/dependabot.yml

We are expecting this to fix the currently not being grouped named dependencies.

fix(dependabot): added explicit `patterns` definition for patch group

---

.github/ISSUE_TEMPLATE/github_copilot_instructions.yaml

Added a new issue template for GitHub Copilot instructions feedback, including fields for model used, prompt examples, issues encountered, expected behavior, suggestions for improvement, clarity rating, and context.

feat: Create GitHub Copilot instructions feedback template
